<?php
$__liste_des_genres=array (
  1 => 
  array (
    'chi_id_genre' => 1,
    'chp_nom_genre' => 'indéfini',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  2 => 
  array (
    'chi_id_genre' => 2,
    'chp_nom_genre' => 'id primaire non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 1,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chi',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  3 => 
  array (
    'chi_id_genre' => 3,
    'chp_nom_genre' => 'varchar 64 non nulle',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  4 => 
  array (
    'chi_id_genre' => 4,
    'chp_nom_genre' => 'espèce',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 1,
    'cht_valeur_init_genre' => 'TEXT',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => 'TEXT,VARCHAR,INTEGER,FLOAT,DECIMAL',
  ),
  5 => 
  array (
    'chi_id_genre' => 5,
    'chp_nom_genre' => 'zero_un non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => '0',
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => '0,1',
  ),
);