<?php
$__liste_des_genres=array (
  1 => 
  array (
    'chi_id_genre' => 1,
    'chp_nom_genre' => '000 indéfini',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  2 => 
  array (
    'chi_id_genre' => 2,
    'chp_nom_genre' => '001 id primaire non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 1,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chi',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  3 => 
  array (
    'chi_id_genre' => 3,
    'chp_nom_genre' => '002 varchar 64 non nulle',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  9 => 
  array (
    'chi_id_genre' => 9,
    'chp_nom_genre' => '003 entier NON NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => '003 entier NULL',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  7 => 
  array (
    'chi_id_genre' => 7,
    'chp_nom_genre' => '003 entier NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  6 => 
  array (
    'chi_id_genre' => 6,
    'chp_nom_genre' => '004 texte NULL',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  5 => 
  array (
    'chi_id_genre' => 5,
    'chp_nom_genre' => '00e zero_un non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => '0',
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => '0,1',
  ),
  4 => 
  array (
    'chi_id_genre' => 4,
    'chp_nom_genre' => '00f lien non null',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chx',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  8 => 
  array (
    'chi_id_genre' => 8,
    'chp_nom_genre' => '00g lien null possible',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chx',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
  ),
  101 => 
  array (
    'chi_id_genre' => 101,
    'chp_nom_genre' => 'espèce',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 1,
    'cht_valeur_init_genre' => 'TEXT',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => 'TEXT,VARCHAR,INTEGER,FLOAT,DECIMAL',
  ),
  102 => 
  array (
    'chi_id_genre' => 102,
    'chp_nom_genre' => 'préfixe',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 3,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 1,
    'cht_valeur_init_genre' => 'cht',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => 'cht,chi,che,chx',
  ),
);