<?php
$__liste_des_genres=array (
  2 => 
  array (
    'chi_id_genre' => 2,
    'chp_nom_genre' => 'id primaire non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 1,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chi',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 1,
  ),
  3 => 
  array (
    'chi_id_genre' => 3,
    'chp_nom_genre' => 'varchar 64 NON NULLE',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 2,
  ),
  12 => 
  array (
    'chi_id_genre' => 12,
    'chp_nom_genre' => 'varchar 64 NULL',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => 'NULL',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 3,
  ),
  4 => 
  array (
    'chi_id_genre' => 4,
    'chp_nom_genre' => 'lien NON NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'chx',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 4,
  ),
  8 => 
  array (
    'chi_id_genre' => 8,
    'chp_nom_genre' => 'lien NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => 'NULL',
    'chp_prefixe_genre' => 'chx',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 5,
  ),
  9 => 
  array (
    'chi_id_genre' => 9,
    'chp_nom_genre' => 'entier NON NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 6,
  ),
  10 => 
  array (
    'chi_id_genre' => 10,
    'chp_nom_genre' => 'entier NON NULL à zéro',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => '0',
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 7,
  ),
  7 => 
  array (
    'chi_id_genre' => 7,
    'chp_nom_genre' => 'entier NULL',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => 'NULL',
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 8,
  ),
  11 => 
  array (
    'chi_id_genre' => 11,
    'chp_nom_genre' => 'texte NON NULL',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 9,
  ),
  6 => 
  array (
    'chi_id_genre' => 6,
    'chp_nom_genre' => 'texte NULL',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => 'NULL',
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 10,
  ),
  5 => 
  array (
    'chi_id_genre' => 5,
    'chp_nom_genre' => 'zero_un non nulle',
    'chp_espece_genre' => 'INTEGER',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => '0',
    'chp_prefixe_genre' => 'che',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => '0,1',
    'che_ordre_genre' => 11,
  ),
  102 => 
  array (
    'chi_id_genre' => 102,
    'chp_nom_genre' => 'préfixe',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 3,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 1,
    'cht_valeur_init_genre' => 'cht',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => 'cht,chi,che,chx',
    'che_ordre_genre' => 12,
  ),
  101 => 
  array (
    'chi_id_genre' => 101,
    'chp_nom_genre' => 'espèce',
    'chp_espece_genre' => 'VARCHAR',
    'che_longueur_genre' => 64,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 1,
    'che_a_init_genre' => 1,
    'che_init_est_mot_genre' => 1,
    'cht_valeur_init_genre' => 'TEXT',
    'chp_prefixe_genre' => 'chp',
    'che_est_parmis_genre' => 1,
    'cht_parmis_genre' => 'TEXT,VARCHAR,INTEGER,FLOAT,DECIMAL',
    'che_ordre_genre' => 13,
  ),
  1 => 
  array (
    'chi_id_genre' => 1,
    'chp_nom_genre' => '***indéfini***',
    'chp_espece_genre' => 'TEXT',
    'che_longueur_genre' => NULL,
    'che_est_primaire_genre' => 0,
    'che_est_incrément_genre' => 0,
    'che_est_obligatoire_genre' => 0,
    'che_a_init_genre' => 0,
    'che_init_est_mot_genre' => 0,
    'cht_valeur_init_genre' => NULL,
    'chp_prefixe_genre' => 'cht',
    'che_est_parmis_genre' => 0,
    'cht_parmis_genre' => NULL,
    'che_ordre_genre' => 14,
  ),
);